// This program source code file is part of KiCad, a free EDA CAD application.
//
// Copyright The KiCad Developers, see AUTHORS.txt for contributors.
//
// This program is free software; you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation; either version 3 of the License, or (at your option) any later
// version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
// details.
//
// You should have received a copy of the GNU General Public License along with
// this program; if not, see <http://www.gnu.org/licenses/>.

//! Hand-written `#[repr(C)]` mirrors of `include/gal/recording/draw_stream_abi.h`.
//!
//! These are deliberately *not* generated by `bindgen`. The header is small,
//! stable and plain C, and hand-mirroring it keeps this crate buildable with no
//! C toolchain and no build script — which matters because the Rust renderer is
//! developed and tested long before the C++ producer exists.
//!
//! Agreement with the header is enforced two ways:
//!
//! * the `const _: () = assert!(...)` layout assertions below, which mirror the
//!   `static_assert`s in the header and fail at compile time; and
//! * [`tests/header_sync.rs`], which reads the header text at test time and
//!   checks that every opcode name and number still matches [`Op`].

// These are raw mirrors: the C header is the documentation for every field, and
// duplicating it here would be one more thing to let drift.
#![allow(non_camel_case_types, missing_docs)]

/// Magic number at the head of a serialised stream: `"KGDS"`, little-endian.
///
/// Mirrors `KGDS_MAGIC`.
pub const KGDS_MAGIC: u32 = 0x5344_474B;

/// ABI version this crate implements. Mirrors `KGDS_VERSION`.
///
/// A stream carrying any other version is rejected rather than guessed at: the
/// header promises that the opcode list, command layout and section table may
/// all change together on a bump.
pub const KGDS_VERSION: u32 = 1;

/// One recorded GAL call. Mirrors `kgds_cmd`; fixed at 24 bytes.
///
/// The meaning of each `arg` slot is opcode-specific; [`crate::Command`] is the
/// resolved form and is what callers should normally use.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub struct kgds_cmd {
    /// A [`Op`] discriminant. Stored raw because an unknown opcode must be
    /// diagnosable rather than undefined.
    pub op: u16,
    /// A bitwise-or of [`flags`] values.
    pub flags: u16,
    pub arg0: u32,
    pub arg1: u32,
    pub arg2: u32,
    pub arg3: u32,
    pub arg4: u32,
}

/// A cached group body, as produced by `GAL::BeginGroup`/`EndGroup`.
///
/// Mirrors `kgds_group`; fixed at 16 bytes. `serial` changes whenever the
/// group's contents are re-recorded, and is the renderer's entire cache
/// invalidation story.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub struct kgds_group {
    /// Stable identity of the group, as referenced by `KGDS_OP_DRAW_GROUP`.
    pub id: u32,
    /// Bumped by the producer whenever the body is re-recorded.
    pub serial: u32,
    /// Index of the first command of the body in the command array.
    pub first_cmd: u32,
    pub cmd_count: u32,
}

/// An embedded bitmap. Mirrors `kgds_image`; fixed at 32 bytes.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub struct kgds_image {
    pub width: u32,
    pub height: u32,
    /// A [`ImageFormat`] discriminant.
    pub format: u32,
    pub reserved: u32,
    /// Byte offset into the image arena.
    pub data_offset: u64,
    pub data_length: u64,
}

/// A borrowed view of a complete stream. Mirrors `kgds_stream_view`.
///
/// This is the struct that crosses the FFI boundary. Every pointer is owned by
/// the producer and stays valid until the next recording pass.
///
/// Retained group geometry and the current frame live in *separate* command
/// arrays and coordinate arenas, and that separation is load-bearing rather
/// than cosmetic: `KIGFX::VIEW` records an item into a group during its update
/// pass and replays it during its draw pass, so the two interleave in time. A
/// command's coordinate indices therefore refer to the arena that command lives
/// in — group bodies index `group_coords`, frame commands index `frame_coords`.
///
/// Its size is asserted to match the C side (136 bytes on a 64-bit target); the
/// assertion is skipped where `size_t` is not 64-bit, since the header's own
/// size is pointer-width dependent.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct kgds_stream_view {
    /// `KGDS_VERSION` the producer was built against.
    pub version: u32,
    pub flags: u32,

    /// Retained geometry, one body per cached item. Indices use `group_coords`.
    pub group_cmds: *const kgds_cmd,
    pub group_cmd_count: usize,

    pub group_coords: *const f64,
    pub group_coord_count: usize,

    /// The group table. Each entry's `first_cmd` indexes `group_cmds`.
    pub groups: *const kgds_group,
    pub group_count: usize,

    /// This frame's command list. Indices use `frame_coords`.
    pub frame_cmds: *const kgds_cmd,
    pub frame_cmd_count: usize,

    pub frame_coords: *const f64,
    pub frame_coord_count: usize,

    pub strings: *const u8,
    pub string_bytes: usize,

    pub images: *const kgds_image,
    pub image_count: usize,

    pub image_data: *const u8,
    pub image_bytes: usize,
}

/// Header of a stream serialised to disk. Mirrors `kgds_file_header`; fixed at
/// 80 bytes. Sections follow in declaration order, each aligned to 8 bytes.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct kgds_file_header {
    pub magic: u32,
    pub version: u32,
    pub flags: u32,
    pub reserved: u32,

    pub group_cmd_count: u64,
    pub group_coord_count: u64,
    pub group_count: u64,
    pub frame_cmd_count: u64,
    pub frame_coord_count: u64,
    pub string_bytes: u64,
    pub image_count: u64,
    pub image_bytes: u64,
}

// Layout agreement is load-bearing across the FFI boundary, so assert it here
// rather than discovering a mismatch as corrupt geometry at runtime. These
// mirror the static_asserts at the foot of the C header.
const _: () = assert!(size_of::<kgds_cmd>() == 24, "kgds_cmd must stay 24 bytes");
const _: () = assert!(size_of::<kgds_group>() == 16, "kgds_group must stay 16 bytes");
const _: () = assert!(size_of::<kgds_image>() == 32, "kgds_image must stay 32 bytes");
const _: () = assert!(
    size_of::<kgds_file_header>() == 80,
    "kgds_file_header must stay 80 bytes"
);

// The C header has no static_assert for the view, because its size depends on
// size_t. Assert it for the 64-bit case we actually ship.
const _: () = assert!(
    size_of::<usize>() != 8 || size_of::<kgds_stream_view>() == 136,
    "kgds_stream_view must stay 136 bytes on 64-bit targets"
);

// Field alignment, which a reordering would silently break even while the total
// size stayed put.
const _: () = assert!(align_of::<kgds_cmd>() == 4);
const _: () = assert!(align_of::<kgds_group>() == 4);
const _: () = assert!(align_of::<kgds_image>() == 8);
const _: () = assert!(align_of::<kgds_file_header>() == 8);

/// Bit flags in [`kgds_cmd::flags`]. Mirrors `enum kgds_flag`.
pub mod flags {
    /// The contour is a hole rather than an outline.
    pub const HOLE: u16 = 1 << 0;
    /// The point run forms a closed loop.
    pub const CLOSED: u16 = 1 << 1;
    /// The geometry came from a glyph. Ordinary geometry; needs no font
    /// support, but the renderer may batch it differently.
    pub const GLYPH: u16 = 1 << 2;

    /// On `DRAW_GROUP`: `arg1` is a packed RGBA8 colour that replaces every
    /// stroke and fill colour inside the group, for this replay only.
    ///
    /// `KIGFX::VIEW` recolours a cached item in place for selection and
    /// highlighting rather than re-recording it, so the override rides on the
    /// replay. That is deliberate and it is what keeps a renderer's
    /// `(id, serial)` cache valid across a selection change — the single most
    /// frequent thing a user does.
    pub const GROUP_COLOR: u16 = 1 << 3;

    /// On `DRAW_GROUP`: `arg2` is a coordinate index to one scalar, the depth
    /// at which to replay the group. Set for the same reason as
    /// [`GROUP_COLOR`].
    pub const GROUP_DEPTH: u16 = 1 << 4;

    /// Every bit this ABI version defines. Unknown bits are rejected so that a
    /// future producer cannot silently lose meaning against an old renderer.
    pub const KNOWN: u16 = HOLE | CLOSED | GLYPH | GROUP_COLOR | GROUP_DEPTH;
}

macro_rules! opcodes {
    ($( $(#[$m:meta])* $name:ident = $value:expr, $c:literal; )*) => {
        /// Draw stream opcodes. Mirrors `enum kgds_op`.
        ///
        /// Numbering is grouped and stable: append within a group, never
        /// renumber. The C spelling of each variant is available via
        /// [`Op::c_name`], which is what `tests/header_sync.rs` compares
        /// against the header text.
        #[repr(u16)]
        #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
        pub enum Op {
            $( $(#[$m])* $name = $value, )*
        }

        impl Op {
            /// Every opcode this ABI version defines, in numeric order.
            pub const ALL: &'static [Op] = &[ $( Op::$name, )* ];

            /// The identifier this opcode has in the C header.
            pub const fn c_name(self) -> &'static str {
                match self { $( Op::$name => $c, )* }
            }

            /// Convert a raw opcode value, returning `None` if it is not one
            /// this ABI version knows.
            ///
            /// Unknown opcodes are never skipped silently: a stream containing
            /// one is rejected, because a command whose argument meaning is
            /// unknown cannot be stepped over safely either.
            pub const fn from_raw(raw: u16) -> Option<Op> {
                match raw {
                    $( $value => Some(Op::$name), )*
                    _ => None,
                }
            }
        }
    };
}

opcodes! {
    // -- 0x00 structural ---------------------------------------------------
    /// No operation.
    Nop = 0x00, "KGDS_OP_NOP";
    /// Begin a frame. `arg0`/`arg1`: viewport width/height in pixels.
    BeginFrame = 0x01, "KGDS_OP_BEGIN_FRAME";
    /// End a frame. No arguments.
    EndFrame = 0x02, "KGDS_OP_END_FRAME";
    /// Clear the screen. `arg0`: packed RGBA8 clear colour.
    ClearScreen = 0x03, "KGDS_OP_CLEAR_SCREEN";
    /// Replay a cached group. `arg0`: the group's id.
    DrawGroup = 0x04, "KGDS_OP_DRAW_GROUP";
    /// Select the render target subsequent commands belong to. `arg0`: a
    /// [`Target`].
    SetTarget = 0x05, "KGDS_OP_SET_TARGET";
    /// Clear a render target. `arg0`: a [`Target`].
    ClearTarget = 0x06, "KGDS_OP_CLEAR_TARGET";
    /// Start a difference-blended layer (pcbnew overlays).
    StartDiffLayer = 0x07, "KGDS_OP_START_DIFF_LAYER";
    /// End a difference-blended layer.
    EndDiffLayer = 0x08, "KGDS_OP_END_DIFF_LAYER";
    /// Start a negatives layer.
    StartNegativesLayer = 0x09, "KGDS_OP_START_NEGATIVES_LAYER";
    /// End a negatives layer.
    EndNegativesLayer = 0x0A, "KGDS_OP_END_NEGATIVES_LAYER";

    // -- 0x10 render state -------------------------------------------------
    /// `arg0`: 0 or 1.
    SetIsFill = 0x10, "KGDS_OP_SET_IS_FILL";
    /// `arg0`: 0 or 1.
    SetIsStroke = 0x11, "KGDS_OP_SET_IS_STROKE";
    /// `arg0`: packed RGBA8.
    SetFillColor = 0x12, "KGDS_OP_SET_FILL_COLOR";
    /// `arg0`: packed RGBA8.
    SetStrokeColor = 0x13, "KGDS_OP_SET_STROKE_COLOR";
    /// `arg0`: packed RGBA8.
    SetHoverColor = 0x14, "KGDS_OP_SET_HOVER_COLOR";
    /// `arg0`: `coords[1]`, the line width in internal units.
    SetLineWidth = 0x15, "KGDS_OP_SET_LINE_WIDTH";
    /// `arg0`: `coords[1]`, a floor applied to stroke widths after scaling.
    SetMinLineWidth = 0x16, "KGDS_OP_SET_MIN_LINE_WIDTH";
    /// `arg0`: `coords[1]`, the painter's-algorithm depth.
    SetLayerDepth = 0x17, "KGDS_OP_SET_LAYER_DEPTH";
    /// `arg0`: 0 or 1.
    SetNegativeDrawMode = 0x18, "KGDS_OP_SET_NEGATIVE_DRAW_MODE";
    /// `arg0`: 0 or 1.
    EnableDepthTest = 0x19, "KGDS_OP_ENABLE_DEPTH_TEST";

    // -- 0x20 transforms ---------------------------------------------------
    /// `arg0`: `coords[6]`, a 3x3 affine as `a b c d e f` (row-major).
    Transform = 0x20, "KGDS_OP_TRANSFORM";
    /// `arg0`: `coords[1]`, radians.
    Rotate = 0x21, "KGDS_OP_ROTATE";
    /// `arg0`: `coords[2]`.
    Translate = 0x22, "KGDS_OP_TRANSLATE";
    /// `arg0`: `coords[2]`.
    Scale = 0x23, "KGDS_OP_SCALE";
    /// Push the transform stack.
    Save = 0x24, "KGDS_OP_SAVE";
    /// Pop the transform stack.
    Restore = 0x25, "KGDS_OP_RESTORE";

    // -- 0x30 geometry -----------------------------------------------------
    /// `arg0`: `coords[4]` = `x0 y0 x1 y1`. Stroked with the current width.
    Line = 0x30, "KGDS_OP_LINE";
    /// `arg0`: `coords[4]`. `arg1`: `coords[1]` = width. Round caps.
    Segment = 0x31, "KGDS_OP_SEGMENT";
    /// `arg0`: `coords[2*n]`. `arg1`: n points. `arg2`: `coords[1]` = width.
    SegmentChain = 0x32, "KGDS_OP_SEGMENT_CHAIN";
    /// `arg0`: `coords[2*n]`. `arg1`: n points.
    Polyline = 0x33, "KGDS_OP_POLYLINE";
    /// `arg0`: `coords[2*n]`. `arg1`: n points.
    Polygon = 0x34, "KGDS_OP_POLYGON";
    /// `arg0`: `coords[3]` = `cx cy r`.
    Circle = 0x35, "KGDS_OP_CIRCLE";
    /// `arg0`: `coords[5]` = `cx cy r start end`, radians.
    Arc = 0x36, "KGDS_OP_ARC";
    /// `arg0`: `coords[5]` as [`Op::Arc`]. `arg1`: `coords[1]` = width.
    ArcSegment = 0x37, "KGDS_OP_ARC_SEGMENT";
    /// `arg0`: `coords[4]` = `x0 y0 x1 y1`, axis-aligned.
    Rectangle = 0x38, "KGDS_OP_RECTANGLE";
    /// `arg0`: `coords[8]` = start, controlA, controlB, end. Cubic Bezier.
    Curve = 0x39, "KGDS_OP_CURVE";
    /// `arg0`: `coords[4]` = `cx cy major minor`. `arg1`: `coords[1]` =
    /// rotation.
    Ellipse = 0x3A, "KGDS_OP_ELLIPSE";
    /// `arg0`: `coords[4]`. `arg1`: `coords[3]` = rotation, start, end.
    /// `arg2`: `coords[1]` = width.
    EllipseArc = 0x3B, "KGDS_OP_ELLIPSE_ARC";
    /// `arg0`: `coords[3]` = `cx cy r`. `arg1`: `coords[1]` = width.
    HoleWall = 0x3C, "KGDS_OP_HOLE_WALL";
    /// `arg0`: image table index. `arg1`: `coords[6]` placement transform.
    /// `arg2`: `coords[1]` alpha.
    Bitmap = 0x3D, "KGDS_OP_BITMAP";

    // -- 0x40 overlays -----------------------------------------------------
    /// `arg0`: `coords[6]` = originX originY sizeX sizeY lineWidthPx style.
    /// `arg1`: packed RGBA8.
    Grid = 0x40, "KGDS_OP_GRID";
    /// `arg0`: `coords[2]` = cursor position. `arg1`: packed RGBA8.
    Cursor = 0x41, "KGDS_OP_CURSOR";
}

/// One run of scalars a command refers to in the coordinate arena.
///
/// Mirrors `kgds_coord_ref`, except that `count` is widened to `u64`. The C
/// function computes a point run's length as `2u * arg1` in `uint32_t`, which
/// wraps for `arg1 >= 2^31`; widening here means a wrapped length shows up as a
/// range error instead of silently naming the wrong bytes.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct CoordRef {
    /// Index of the first scalar.
    pub start: u32,
    /// Number of scalars.
    pub count: u64,
}

/// The `kgds_coord_ref` record exactly as C lays it out, for the rare caller
/// that needs to exchange one across the boundary. Prefer [`CoordRef`].
#[repr(C)]
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct kgds_coord_ref {
    pub start: u32,
    pub count: u32,
}

const _: () = assert!(size_of::<kgds_coord_ref>() == 8);

/// Upper bound on the number of coordinate runs any single command refers to.
/// Mirrors `KGDS_MAX_COORD_REFS`.
pub const MAX_COORD_REFS: usize = 3;

/// The coordinate runs a single command refers to.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct CoordRefs {
    refs: [CoordRef; MAX_COORD_REFS],
    len: usize,
}

impl CoordRefs {
    /// The runs, in the order the C function writes them.
    pub fn as_slice(&self) -> &[CoordRef] {
        &self.refs[..self.len]
    }

    fn push(&mut self, start: u32, count: u64) {
        self.refs[self.len] = CoordRef { start, count };
        self.len += 1;
    }
}

impl std::ops::Deref for CoordRefs {
    type Target = [CoordRef];
    fn deref(&self) -> &[CoordRef] {
        self.as_slice()
    }
}

/// Report which runs of the coordinate arena a command refers to.
///
/// The Rust twin of `kgds_coord_refs`, which the header calls the single source
/// of truth for this mapping: the producer relocates live geometry with it when
/// it compacts an arena, and this crate bounds-checks a stream with it. The two
/// must agree exactly, and `tests/header_sync.rs` parses the C function and
/// compares it against this one to make sure they do.
///
/// Commands that carry no coordinates — state changes, group references, frame
/// markers — return no runs. So does an unrecognised opcode, matching the C
/// `default` arm; callers must reject unknown opcodes separately rather than
/// reading an empty result as "nothing to check".
pub fn coord_refs(cmd: &kgds_cmd) -> CoordRefs {
    let mut out = CoordRefs::default();
    let Some(op) = Op::from_raw(cmd.op) else {
        return out;
    };

    // A point run holds two scalars per point; computed in u64 so that a
    // hostile count fails a range check rather than wrapping into a small one.
    let run = |n: u32| -> u64 { 2 * (n as u64) };

    match op {
        Op::SetLineWidth | Op::SetMinLineWidth | Op::SetLayerDepth | Op::Rotate => {
            out.push(cmd.arg0, 1)
        }
        Op::Translate | Op::Scale | Op::Cursor => out.push(cmd.arg0, 2),
        Op::Transform | Op::Grid => out.push(cmd.arg0, 6),
        Op::Line | Op::Rectangle => out.push(cmd.arg0, 4),
        Op::Segment => {
            out.push(cmd.arg0, 4);
            out.push(cmd.arg1, 1);
        }
        Op::SegmentChain => {
            out.push(cmd.arg0, run(cmd.arg1));
            out.push(cmd.arg2, 1);
        }
        Op::Polyline | Op::Polygon => out.push(cmd.arg0, run(cmd.arg1)),
        Op::Circle => out.push(cmd.arg0, 3),
        Op::HoleWall => {
            out.push(cmd.arg0, 3);
            out.push(cmd.arg1, 1);
        }
        Op::Arc => out.push(cmd.arg0, 5),
        Op::ArcSegment => {
            out.push(cmd.arg0, 5);
            out.push(cmd.arg1, 1);
        }
        Op::Curve => out.push(cmd.arg0, 8),
        Op::Ellipse => {
            out.push(cmd.arg0, 4);
            out.push(cmd.arg1, 1);
        }
        Op::EllipseArc => {
            out.push(cmd.arg0, 4);
            out.push(cmd.arg1, 3);
            out.push(cmd.arg2, 1);
        }
        Op::Bitmap => {
            // arg0 is an image table index, not a coordinate.
            out.push(cmd.arg1, 6);
            out.push(cmd.arg2, 1);
        }
        Op::DrawGroup => {
            // arg0 is a group id, not a coordinate. Only the optional depth
            // override refers to the arena.
            if cmd.flags & flags::GROUP_DEPTH != 0 {
                out.push(cmd.arg2, 1);
            }
        }
        Op::Nop
        | Op::BeginFrame
        | Op::EndFrame
        | Op::ClearScreen
        | Op::SetTarget
        | Op::ClearTarget
        | Op::StartDiffLayer
        | Op::EndDiffLayer
        | Op::StartNegativesLayer
        | Op::EndNegativesLayer
        | Op::SetIsFill
        | Op::SetIsStroke
        | Op::SetFillColor
        | Op::SetStrokeColor
        | Op::SetHoverColor
        | Op::SetNegativeDrawMode
        | Op::EnableDepthTest
        | Op::Save
        | Op::Restore => {}
    }

    out
}

/// Render target. Mirrors `kgds_target`, which matches `KIGFX::RENDER_TARGET`.
#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Default)]
pub enum Target {
    #[default]
    Cached = 0,
    NonCached = 1,
    Overlay = 2,
    Temp = 3,
}

impl Target {
    /// Convert a raw target value, returning `None` if unknown.
    pub const fn from_raw(raw: u32) -> Option<Target> {
        match raw {
            0 => Some(Target::Cached),
            1 => Some(Target::NonCached),
            2 => Some(Target::Overlay),
            3 => Some(Target::Temp),
            _ => None,
        }
    }
}

/// Pixel format of an image table entry. Mirrors `kgds_image_format`.
#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Default)]
pub enum ImageFormat {
    #[default]
    Rgba8 = 0,
}

impl ImageFormat {
    /// Bytes per pixel for this format.
    pub const fn bytes_per_pixel(self) -> u64 {
        match self {
            ImageFormat::Rgba8 => 4,
        }
    }

    /// Convert a raw format value, returning `None` if unknown.
    pub const fn from_raw(raw: u32) -> Option<ImageFormat> {
        match raw {
            0 => Some(ImageFormat::Rgba8),
            _ => None,
        }
    }
}

/// Grid style, as carried in the sixth grid coordinate.
///
/// Mirrors `KIGFX::GRID_STYLE` in `include/gal/gal_display_options.h`; the
/// draw stream passes it through as a `double` rather than adding an enum to
/// the ABI.
#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Default)]
pub enum GridStyle {
    /// A dot at each grid intersection.
    #[default]
    Dots = 0,
    /// Full horizontal and vertical lines.
    Lines = 1,
    /// A small cross at each intersection.
    SmallCross = 2,
}

impl GridStyle {
    /// Convert a raw style value, returning `None` if unknown.
    pub const fn from_raw(raw: u32) -> Option<GridStyle> {
        match raw {
            0 => Some(GridStyle::Dots),
            1 => Some(GridStyle::Lines),
            2 => Some(GridStyle::SmallCross),
            _ => None,
        }
    }
}

/// An RGBA colour as carried in a packed-RGBA8 command argument.
///
/// The packing is the one `kgds_pack_color` performs: red in the low byte,
/// alpha in the high byte.
#[derive(Clone, Copy, Debug, PartialEq, Default)]
pub struct Color {
    pub r: f32,
    pub g: f32,
    pub b: f32,
    pub a: f32,
}

impl Color {
    /// Fully opaque black.
    pub const BLACK: Color = Color { r: 0.0, g: 0.0, b: 0.0, a: 1.0 };
    /// Fully opaque white.
    pub const WHITE: Color = Color { r: 1.0, g: 1.0, b: 1.0, a: 1.0 };
    /// Fully transparent.
    pub const TRANSPARENT: Color = Color { r: 0.0, g: 0.0, b: 0.0, a: 0.0 };

    /// Construct from components in `[0, 1]`.
    pub const fn new(r: f32, g: f32, b: f32, a: f32) -> Color {
        Color { r, g, b, a }
    }

    /// Unpack the RGBA8 representation used in command arguments.
    pub fn from_packed(packed: u32) -> Color {
        Color {
            r: (packed & 0xFF) as f32 / 255.0,
            g: ((packed >> 8) & 0xFF) as f32 / 255.0,
            b: ((packed >> 16) & 0xFF) as f32 / 255.0,
            a: ((packed >> 24) & 0xFF) as f32 / 255.0,
        }
    }

    /// Pack to RGBA8 exactly as `kgds_pack_color` does, clamping first because
    /// `COLOR4D` values can leave the unit range after blending.
    pub fn to_packed(self) -> u32 {
        fn q(v: f32) -> u32 {
            let c = if v < 0.0 {
                0.0
            } else if v > 1.0 {
                1.0
            } else {
                v as f64
            };
            (c * 255.0 + 0.5) as u32
        }
        q(self.r) | (q(self.g) << 8) | (q(self.b) << 16) | (q(self.a) << 24)
    }
}

/// Pack four components in `[0, 1]` into RGBA8. The Rust twin of
/// `kgds_pack_color`, kept so callers can reproduce the producer bit for bit.
pub fn pack_color(r: f64, g: f64, b: f64, a: f64) -> u32 {
    let q = |v: f64| -> u32 {
        let c = v.clamp(0.0, 1.0);
        (c * 255.0 + 0.5) as u32
    };
    q(r) | (q(g) << 8) | (q(b) << 16) | (q(a) << 24)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn color_round_trips_through_packing() {
        for packed in [0u32, 0xFFFF_FFFF, 0x1234_5678, 0x0080_80FF] {
            assert_eq!(Color::from_packed(packed).to_packed(), packed);
        }
    }

    #[test]
    fn pack_color_clamps_out_of_range_components() {
        assert_eq!(pack_color(-1.0, 2.0, 0.0, 1.0), 0xFF00_FF00);
    }

    #[test]
    fn opcodes_are_unique_and_ordered() {
        let mut prev: i32 = -1;
        for op in Op::ALL {
            let v = *op as i32;
            assert!(v > prev, "opcode {} out of order", op.c_name());
            prev = v;
        }
    }

    #[test]
    fn unknown_opcode_is_rejected_not_guessed() {
        assert!(Op::from_raw(0x42).is_none());
        assert!(Op::from_raw(0xFFFF).is_none());
        assert_eq!(Op::from_raw(0x30), Some(Op::Line));
    }
}
